import hljs from "highlight.js/lib/core";
import javascript from "highlight.js/lib/languages/javascript";
import python from "highlight.js/lib/languages/python";
import cpp from "highlight.js/lib/languages/cpp";
import c from "highlight.js/lib/languages/c";
import java from "highlight.js/lib/languages/java";
import xml from "highlight.js/lib/languages/xml";
import bash from "highlight.js/lib/languages/bash";
import css from 'highlight.js/lib/languages/css';
import php from 'highlight.js/lib/languages/php';
import ruby from 'highlight.js/lib/languages/ruby';
import go from 'highlight.js/lib/languages/go';
import kotlin from 'highlight.js/lib/languages/kotlin';
import swift from 'highlight.js/lib/languages/swift';
import typescript from 'highlight.js/lib/languages/typescript';
import json from 'highlight.js/lib/languages/json';
import markdown from 'highlight.js/lib/languages/markdown';
import sql from 'highlight.js/lib/languages/sql';
import csharp from 'highlight.js/lib/languages/csharp';
import objectivec from 'highlight.js/lib/languages/objectivec';
import rust from 'highlight.js/lib/languages/rust';
import perl from 'highlight.js/lib/languages/perl';
import lua from 'highlight.js/lib/languages/lua';
import groovy from 'highlight.js/lib/languages/groovy';
import dockerfile from 'highlight.js/lib/languages/dockerfile';
import yaml from 'highlight.js/lib/languages/yaml';
import ini from 'highlight.js/lib/languages/ini';
import arduino from 'highlight.js/lib/languages/arduino';
import powershell from 'highlight.js/lib/languages/powershell';
import less from 'highlight.js/lib/languages/less';
import scss from 'highlight.js/lib/languages/scss';
import handlebars from 'highlight.js/lib/languages/handlebars';
import django from 'highlight.js/lib/languages/django';
import elixir from 'highlight.js/lib/languages/elixir';
import erlang from 'highlight.js/lib/languages/erlang';
import haskell from 'highlight.js/lib/languages/haskell';
import julia from 'highlight.js/lib/languages/julia';
import matlab from 'highlight.js/lib/languages/matlab';
import r from 'highlight.js/lib/languages/r';
import scala from 'highlight.js/lib/languages/scala';
import smalltalk from 'highlight.js/lib/languages/smalltalk';
import vbnet from 'highlight.js/lib/languages/vbnet';
import delphi from 'highlight.js/lib/languages/delphi';
import ada from 'highlight.js/lib/languages/ada';
import assembly from 'highlight.js/lib/languages/x86asm';
import coffeescript from 'highlight.js/lib/languages/coffeescript';
import fsharp from 'highlight.js/lib/languages/fsharp';
import lisp from 'highlight.js/lib/languages/lisp';
import scheme from 'highlight.js/lib/languages/scheme';
// import pascal from 'highlight.js/lib/languages/pascal';
import prolog from 'highlight.js/lib/languages/prolog';
import tcl from 'highlight.js/lib/languages/tcl';
import vim from 'highlight.js/lib/languages/vim';
import d from 'highlight.js/lib/languages/d';
import fortran from 'highlight.js/lib/languages/fortran';
import graphql from 'highlight.js/lib/languages/graphql';
import stylus from 'highlight.js/lib/languages/stylus';
import twig from 'highlight.js/lib/languages/twig';
import actionscript from 'highlight.js/lib/languages/actionscript';
import apache from 'highlight.js/lib/languages/apache';
import applescript from 'highlight.js/lib/languages/applescript';
import asciidoc from 'highlight.js/lib/languages/asciidoc';
import autohotkey from 'highlight.js/lib/languages/autohotkey';
import awk from 'highlight.js/lib/languages/awk';
import brainfuck from 'highlight.js/lib/languages/brainfuck';
import clojure from 'highlight.js/lib/languages/clojure';
import cmake from 'highlight.js/lib/languages/cmake';
import crystal from 'highlight.js/lib/languages/crystal';
import glsl from 'highlight.js/lib/languages/glsl';
import gml from 'highlight.js/lib/languages/gml';
import gradle from 'highlight.js/lib/languages/gradle';
import haml from 'highlight.js/lib/languages/haml';
import http from 'highlight.js/lib/languages/http';
import jbossCli from 'highlight.js/lib/languages/jboss-cli';
import latex from 'highlight.js/lib/languages/latex';
import ldif from 'highlight.js/lib/languages/ldif';
import livecodeserver from 'highlight.js/lib/languages/livecodeserver';
import llvm from 'highlight.js/lib/languages/llvm';
import makefile from 'highlight.js/lib/languages/makefile';
import mel from 'highlight.js/lib/languages/mel';
import mercury from 'highlight.js/lib/languages/mercury';
import mipsasm from 'highlight.js/lib/languages/mipsasm';
import nginx from 'highlight.js/lib/languages/nginx';
import nim from 'highlight.js/lib/languages/nim';
import nsis from 'highlight.js/lib/languages/nsis';
import ocaml from 'highlight.js/lib/languages/ocaml';
import openscad from 'highlight.js/lib/languages/openscad';
import oxygene from 'highlight.js/lib/languages/oxygene';
import pf from 'highlight.js/lib/languages/pf';
import processing from 'highlight.js/lib/languages/processing';
import qml from 'highlight.js/lib/languages/qml';
import reasonml from 'highlight.js/lib/languages/reasonml';
import roboconf from 'highlight.js/lib/languages/roboconf';
import routeros from 'highlight.js/lib/languages/routeros';
import rsl from 'highlight.js/lib/languages/rsl';
import ruleslanguage from 'highlight.js/lib/languages/ruleslanguage';
import sas from 'highlight.js/lib/languages/sas';
import scilab from 'highlight.js/lib/languages/scilab';
import smali from 'highlight.js/lib/languages/smali';
import stan from 'highlight.js/lib/languages/stan';
import stata from 'highlight.js/lib/languages/stata';
import step21 from 'highlight.js/lib/languages/step21';
import taggerscript from 'highlight.js/lib/languages/taggerscript';
import tap from 'highlight.js/lib/languages/tap';
import thrift from 'highlight.js/lib/languages/thrift';
import tp from 'highlight.js/lib/languages/tp';
import vala from 'highlight.js/lib/languages/vala';
import vbscript from 'highlight.js/lib/languages/vbscript';
import vhdl from 'highlight.js/lib/languages/vhdl';
// import webgl from 'highlight.js/lib/languages/webgl';
import x86asm from 'highlight.js/lib/languages/x86asm';
// import xlq from 'highlight.js/lib/languages/xlq';
import zephir from 'highlight.js/lib/languages/zephir';

hljs.registerLanguage("javascript", javascript);
hljs.registerLanguage("python", python);
hljs.registerLanguage("cpp", cpp);
hljs.registerLanguage("c", c);
hljs.registerLanguage("java", java);
hljs.registerLanguage("html", xml); // Using xml for HTML
hljs.registerLanguage("bash", bash);
hljs.registerLanguage('css', css);
hljs.registerLanguage('php', php);
hljs.registerLanguage('ruby', ruby);
hljs.registerLanguage('go', go);
hljs.registerLanguage('kotlin', kotlin);
hljs.registerLanguage('swift', swift);
hljs.registerLanguage('typescript', typescript);
hljs.registerLanguage('json', json);
hljs.registerLanguage('markdown', markdown);
hljs.registerLanguage('sql', sql);
hljs.registerLanguage('csharp', csharp);
hljs.registerLanguage('objectivec', objectivec);
hljs.registerLanguage('rust', rust);
hljs.registerLanguage('perl', perl);
hljs.registerLanguage('lua', lua);
hljs.registerLanguage('groovy', groovy);
hljs.registerLanguage('dockerfile', dockerfile);
hljs.registerLanguage('yaml', yaml);
hljs.registerLanguage('ini', ini);
hljs.registerLanguage('arduino', arduino);
hljs.registerLanguage('powershell', powershell);
hljs.registerLanguage('less', less);
hljs.registerLanguage('scss', scss);
hljs.registerLanguage('handlebars', handlebars);
hljs.registerLanguage('django', django);
hljs.registerLanguage('elixir', elixir);
hljs.registerLanguage('erlang', erlang);
hljs.registerLanguage('haskell', haskell);
hljs.registerLanguage('julia', julia);
hljs.registerLanguage('matlab', matlab);
hljs.registerLanguage('r', r);
hljs.registerLanguage('scala', scala);
hljs.registerLanguage('smalltalk', smalltalk);
hljs.registerLanguage('vbnet', vbnet);
hljs.registerLanguage('delphi', delphi);
hljs.registerLanguage('ada', ada);
hljs.registerLanguage('assembly', assembly);
hljs.registerLanguage('coffeescript', coffeescript);
hljs.registerLanguage('fsharp', fsharp);
hljs.registerLanguage('lisp', lisp);
hljs.registerLanguage('scheme', scheme);
// hljs.registerLanguage('pascal', pascal);
hljs.registerLanguage('prolog', prolog);
hljs.registerLanguage('tcl', tcl);
hljs.registerLanguage('vim', vim);
hljs.registerLanguage('d', d);
hljs.registerLanguage('fortran', fortran);
hljs.registerLanguage('graphql', graphql);
hljs.registerLanguage('stylus', stylus);
hljs.registerLanguage('twig', twig);
hljs.registerLanguage('actionscript', actionscript);
hljs.registerLanguage('apache', apache);
hljs.registerLanguage('applescript', applescript);
hljs.registerLanguage('asciidoc', asciidoc);
hljs.registerLanguage('autohotkey', autohotkey);
hljs.registerLanguage('awk', awk);
hljs.registerLanguage('brainfuck', brainfuck);
hljs.registerLanguage('clojure', clojure);
hljs.registerLanguage('cmake', cmake);
hljs.registerLanguage('crystal', crystal);
hljs.registerLanguage('glsl', glsl);
hljs.registerLanguage('gml', gml);
hljs.registerLanguage('gradle', gradle);
hljs.registerLanguage('haml', haml);
hljs.registerLanguage('http', http);
hljs.registerLanguage('jboss-cli', jbossCli);
hljs.registerLanguage('latex', latex);
hljs.registerLanguage('ldif', ldif);
hljs.registerLanguage('livecodeserver', livecodeserver);
hljs.registerLanguage('llvm', llvm);
hljs.registerLanguage('makefile', makefile);
hljs.registerLanguage('mel', mel);
hljs.registerLanguage('mercury', mercury);
hljs.registerLanguage('mipsasm', mipsasm);
hljs.registerLanguage('nginx', nginx);
hljs.registerLanguage('nim', nim);
hljs.registerLanguage('nsis', nsis);
hljs.registerLanguage('ocaml', ocaml);
hljs.registerLanguage('openscad', openscad);
hljs.registerLanguage('oxygene', oxygene);
hljs.registerLanguage('pf', pf);
hljs.registerLanguage('processing', processing);
hljs.registerLanguage('qml', qml);
hljs.registerLanguage('reasonml', reasonml);
hljs.registerLanguage('roboconf', roboconf);
hljs.registerLanguage('routeros', routeros);
hljs.registerLanguage('rsl', rsl);
hljs.registerLanguage('ruleslanguage', ruleslanguage);
hljs.registerLanguage('sas', sas);
hljs.registerLanguage('scilab', scilab);
hljs.registerLanguage('smali', smali);
hljs.registerLanguage('stan', stan);
hljs.registerLanguage('stata', stata);
hljs.registerLanguage('step21', step21);
hljs.registerLanguage('taggerscript', taggerscript);
hljs.registerLanguage('tap', tap);
hljs.registerLanguage('thrift', thrift);
hljs.registerLanguage('tp', tp);
hljs.registerLanguage('vala', vala);
hljs.registerLanguage('vbscript', vbscript);
hljs.registerLanguage('vhdl', vhdl);
// hljs.registerLanguage('webgl', webgl);
hljs.registerLanguage('x86asm', x86asm);
// hljs.registerLanguage('xlq', xlq);
hljs.registerLanguage('zephir', zephir);

export default hljs;
